# Generated by Django 3.0.9 on 2020-09-02 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_type',
            new_name='article_type_id',
        ),
    ]
